config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/steam_request', to: 'pages#try_again', as: 'tryagain'
  post '/steam_request', to: 'pages#steam_request', as: 'steamrequest'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/statistic.rb
class Statistic < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
require 'open-uri'
require 'json'

URL = "https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=XXXXXXXXXXXXXXXXX&steamid=76561197960434622&format=json"

class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[home try_again steam_request]

  def home; end

  def try_again; end

  def steam_request
    steam_id = params[:steam_id][:steam_id]
    response = JSON.parse(open("http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=#{ENV['STEAM_API']}&steamid=#{steam_id}&include_appinfo=true&include_played_free_games=true&format=json").read)
    @statistics = Statistic.all
    @sorted_games = response["response"]["games"].sort_by { |game| game["playtime_forever"] }.reverse.first(10)
    rescue OpenURI::HTTPError => e
    if e
      flash[:notice] = "Either the ID you provided is not valid or something has gone horribly wrong. Try again."
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SteamyStats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container" style="text-align: center; margin-top: 300px;">
  <h1>Welcome to Steamy Stats</h1>
  <h4>Find out how the time you've spent playing games on Steam translates to other things you could've done in the same timeframe.</h4>
  <%= simple_form_for :steam_id, url: steamrequest_path do |f| %>
    <%= f.input :steam_id, label: "Steam ID" %>
    <%= f.submit "Mock Me" %>
  <% end %>
</div>

app/views/pages/steam_request.html.erb
<div class="container">
  <h1 style="text-align: center; margin-top: 50px;">You should be ashamed of yourself</h1>
  <div style="text-align: center; margin-top: 10px;">
    <img src="https://media.giphy.com/media/vX9WcCiWwUF7G/giphy.gif" alt="" style="border-radius: 20px;">
  </div>
    <div style="display: flex; align-items: center; justify-content: center; flex-wrap: wrap;">
      <% total_time = 0  %>
      <% @sorted_games.each do |game| %>
        <div style="width: 300px; background-color: lightgrey; margin: 20px; align-items: center; text-align: center; border-radius: 10px; padding: 20px;">
          <% time = (game["playtime_forever"].to_i / 60.0).round(1) %>
          <% statistic = @statistics.sample %>
          <% total_time += game["playtime_forever"].to_i %>
          <p><%= game["name"] %></p>
          <p>Hours spent playing:</p>
          <h3><%= time %></h2>
          <p>Within the time you spent playing <%= game["name"] %> you could have <%= statistic.description %> <%= (game["playtime_forever"].to_i / statistic.time).round(1) %> time<%= "s" unless (game["playtime_forever"].to_i / statistic.time).round(1) == 1 %></p>
        </div>
      <% end %>
    </div>
    <% if total_time / 224109 >= 1 %>
      <p class="bg-danger" style="opacity: 0.8; padding: 20px; border-radius: 20px; text-align: center;">Within the time you've spent playing those ten games, you could have ran around the equator <%= (total_time / 224109).round(1) %> time<%= "s" unless (total_time / 224109).round(1) == 1 %>.</p>
    <% end %>
</div>

app/views/pages/try_again.html.erb
<div class="container" style="text-align: center; margin-top: 350px;">
  <h2>We do not keep any of the data you have entered and therefore going back and forth or refreshing will not work due to the way the application is made.</h2>
  <h4 style="margin-top: 30px;">Please <%= link_to "go back", root_path  %> to the main page and enter the Steam ID you wish to check again.</h4>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>